version: '3'
services:
  pet-shop-api:
    container_name: pet-shop-api
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - /vendor
      - ./:/var/www/html
    ports:
      - 3000:8000
    depends_on:
      - pet-shop-db
      - pet-shop-redis
    networks:
      - pet-shop-net
  pet-shop-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    container_name: pet-shop-db
    ports:
      - 3307:3306
      - 3308:3306
    volumes:
      - ./:/data
      - pet-shop-data:/var/lib/mysql
    networks:
      - pet-shop-net
  pet-shop-redis:
    image: redis:latest
    container_name: pet-shop-redis
    networks:
      - pet-shop-net
volumes:
  pet-shop-data:
  pet-shop-data-test:
networks:
  pet-shop-net:
